/**
 * AI Image Component
 *
 * Display images generated by AI models (like Gemini's image generation).
 * Supports multiple input formats:
 * - Base64 encoded strings
 * - Uint8Array binary data
 * - URLs (local or remote)
 *
 * Features:
 * - Loading state with skeleton
 * - Error handling with retry
 * - Lightbox for full-screen view
 * - Download action
 * - Copy to clipboard
 *
 * @package @cadhy/ui
 */

"use client"

import {
  Cancel01Icon,
  Copy01Icon,
  Download01Icon,
  Image01Icon,
  Loading01Icon,
  ZoomIcon,
} from "@hugeicons/core-free-icons"
import { HugeiconsIcon } from "@hugeicons/react"
import type { ComponentProps, ReactNode } from "react"
import {
  createContext,
  forwardRef,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useState,
} from "react"

import { cn } from "../../lib/utils"
import { Button } from "../button"
import { Dialog, DialogContent, DialogOverlay, DialogPortal, DialogTrigger } from "../dialog"

// ============================================================================
// TYPES
// ============================================================================

export type AIImageStatus = "loading" | "loaded" | "error"

export interface AIImageData {
  /** Base64 encoded image data (without data URL prefix) */
  base64?: string
  /** Binary image data */
  uint8Array?: Uint8Array
  /** Direct URL to image */
  url?: string
  /** MIME type of the image */
  mediaType?: string
  /** Alt text for accessibility */
  alt?: string
}

// ============================================================================
// CONTEXT
// ============================================================================

interface AIImageContextValue {
  src: string | null
  status: AIImageStatus
  mediaType: string
  alt: string
  retry: () => void
  download: () => void
  copyToClipboard: () => Promise<void>
}

const AIImageContext = createContext<AIImageContextValue | null>(null)

function useAIImage() {
  const context = useContext(AIImageContext)
  if (!context) {
    throw new Error("useAIImage must be used within AIImageProvider")
  }
  return context
}

// ============================================================================
// UTILS
// ============================================================================

function uint8ArrayToBase64(bytes: Uint8Array): string {
  let binary = ""
  const len = bytes.byteLength
  for (let i = 0; i < len; i++) {
    binary += String.fromCharCode(bytes[i] ?? 0)
  }
  return btoa(binary)
}

function getDataUrl(base64: string, mediaType: string): string {
  return `data:${mediaType};base64,${base64}`
}

// ============================================================================
// AI IMAGE (Main Container)
// ============================================================================

export interface AIImageProps extends Omit<ComponentProps<"div">, "children"> {
  /** Image data from AI generation */
  data: AIImageData
  /** Children (compose with AIImagePreview, AIImageActions, etc.) */
  children?: ReactNode
}

export function AIImage({ data, children, className, ...props }: AIImageProps) {
  const [status, setStatus] = useState<AIImageStatus>("loading")
  const [_retryCount, setRetryCount] = useState(0)

  const mediaType = data.mediaType || "image/png"
  const alt = data.alt || "AI generated image"

  // Convert data to displayable src
  const src = useMemo(() => {
    if (data.url) {
      return data.url
    }
    if (data.base64) {
      return getDataUrl(data.base64, mediaType)
    }
    if (data.uint8Array) {
      const base64 = uint8ArrayToBase64(data.uint8Array)
      return getDataUrl(base64, mediaType)
    }
    return null
  }, [data.url, data.base64, data.uint8Array, mediaType])

  // Handle loading/error states
  useEffect(() => {
    if (!src) {
      setStatus("error")
      return
    }

    setStatus("loading")
    const img = new Image()
    img.onload = () => setStatus("loaded")
    img.onerror = () => setStatus("error")
    img.src = src
  }, [src])

  const retry = useCallback(() => {
    setRetryCount((c) => c + 1)
  }, [])

  const download = useCallback(() => {
    if (!src) return

    const link = document.createElement("a")
    link.href = src
    link.download = `ai-image-${Date.now()}.${mediaType.split("/")[1] || "png"}`
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
  }, [src, mediaType])

  const copyToClipboard = useCallback(async () => {
    if (!src) return

    try {
      // For data URLs, we need to convert to blob first
      const response = await fetch(src)
      const blob = await response.blob()
      await navigator.clipboard.write([new ClipboardItem({ [blob.type]: blob })])
    } catch (error) {
      console.error("Failed to copy image to clipboard:", error)
      throw error
    }
  }, [src])

  const contextValue = useMemo<AIImageContextValue>(
    () => ({
      src,
      status,
      mediaType,
      alt,
      retry,
      download,
      copyToClipboard,
    }),
    [src, status, mediaType, alt, retry, download, copyToClipboard]
  )

  return (
    <AIImageContext.Provider value={contextValue}>
      <div data-slot="ai-image" className={cn("relative inline-block", className)} {...props}>
        {children || <AIImagePreview />}
      </div>
    </AIImageContext.Provider>
  )
}

// ============================================================================
// AI IMAGE PREVIEW
// ============================================================================

export interface AIImagePreviewProps extends ComponentProps<"div"> {
  /** Width of the preview */
  width?: number | string
  /** Height of the preview */
  height?: number | string
  /** Object fit mode */
  objectFit?: "contain" | "cover" | "fill" | "none" | "scale-down"
  /** Show loading skeleton */
  showSkeleton?: boolean
  /** Enable lightbox on click */
  lightbox?: boolean
}

export const AIImagePreview = forwardRef<HTMLDivElement, AIImagePreviewProps>(
  (
    {
      width = 256,
      height = 256,
      objectFit = "cover",
      showSkeleton = true,
      lightbox = true,
      className,
      ...props
    },
    ref
  ) => {
    const { src, status, alt } = useAIImage()
    const [isOpen, setIsOpen] = useState(false)

    const imageElement = (
      <div
        ref={ref}
        data-slot="ai-image-preview"
        className={cn(
          "relative overflow-hidden rounded-2xl bg-muted",
          status === "loading" && showSkeleton && "animate-pulse",
          lightbox && status === "loaded" && "cursor-zoom-in",
          className
        )}
        style={{ width, height }}
        onClick={lightbox && status === "loaded" ? () => setIsOpen(true) : undefined}
        {...props}
      >
        {status === "loading" && showSkeleton && (
          <div className="absolute inset-0 flex items-center justify-center">
            <HugeiconsIcon
              icon={Loading01Icon}
              className="size-6 text-muted-foreground animate-spin"
            />
          </div>
        )}

        {status === "error" && (
          <div className="absolute inset-0 flex flex-col items-center justify-center gap-2">
            <HugeiconsIcon icon={Image01Icon} className="size-8 text-muted-foreground" />
            <span className="text-xs text-muted-foreground">Failed to load</span>
          </div>
        )}

        {status === "loaded" && src && (
          <>
            <img src={src} alt={alt} className="h-full w-full" style={{ objectFit }} />
            {lightbox && (
              <div className="absolute inset-0 flex items-center justify-center bg-black/40 opacity-0 transition-opacity hover:opacity-100">
                <HugeiconsIcon icon={ZoomIcon} className="size-8 text-white" />
              </div>
            )}
          </>
        )}
      </div>
    )

    if (!lightbox) {
      return imageElement
    }

    return (
      <Dialog open={isOpen} onOpenChange={setIsOpen}>
        <DialogTrigger asChild>{imageElement}</DialogTrigger>
        <DialogPortal>
          <DialogOverlay className="bg-black/80" />
          <DialogContent className="max-w-[90vw] max-h-[90vh] p-0 border-none bg-transparent">
            <button
              onClick={() => setIsOpen(false)}
              className="absolute right-4 top-4 z-50 rounded-full bg-black/50 p-2 text-white hover:bg-black/70 transition-colors"
            >
              <HugeiconsIcon icon={Cancel01Icon} className="size-5" />
              <span className="sr-only">Close</span>
            </button>
            {src && (
              <img
                src={src}
                alt={alt}
                className="max-w-full max-h-[90vh] rounded-2xl object-contain"
              />
            )}
          </DialogContent>
        </DialogPortal>
      </Dialog>
    )
  }
)
AIImagePreview.displayName = "AIImagePreview"

// ============================================================================
// AI IMAGE ACTIONS
// ============================================================================

export type AIImageActionsProps = ComponentProps<"div">

export function AIImageActions({ children, className, ...props }: AIImageActionsProps) {
  return (
    <div
      data-slot="ai-image-actions"
      className={cn(
        "absolute bottom-2 right-2 flex items-center gap-1 rounded-2xl bg-black/50 p-1",
        "opacity-0 transition-opacity group-hover:opacity-100",
        className
      )}
      {...props}
    >
      {children || (
        <>
          <AIImageDownloadButton />
          <AIImageCopyButton />
        </>
      )}
    </div>
  )
}

// ============================================================================
// AI IMAGE DOWNLOAD BUTTON
// ============================================================================

export interface AIImageDownloadButtonProps extends ComponentProps<typeof Button> {}

export function AIImageDownloadButton({ className, ...props }: AIImageDownloadButtonProps) {
  const { download, status } = useAIImage()

  return (
    <Button
      type="button"
      variant="ghost"
      size="icon-xs"
      className={cn("size-7 text-white hover:bg-white/20", className)}
      onClick={download}
      disabled={status !== "loaded"}
      {...props}
    >
      <HugeiconsIcon icon={Download01Icon} className="size-4" />
      <span className="sr-only">Download</span>
    </Button>
  )
}

// ============================================================================
// AI IMAGE COPY BUTTON
// ============================================================================

export interface AIImageCopyButtonProps extends ComponentProps<typeof Button> {}

export function AIImageCopyButton({ className, ...props }: AIImageCopyButtonProps) {
  const { copyToClipboard, status } = useAIImage()
  const [copied, setCopied] = useState(false)

  const handleCopy = useCallback(async () => {
    try {
      await copyToClipboard()
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch {
      // Error is already logged in copyToClipboard
    }
  }, [copyToClipboard])

  return (
    <Button
      type="button"
      variant="ghost"
      size="icon-xs"
      className={cn("size-7 text-white hover:bg-white/20", className)}
      onClick={handleCopy}
      disabled={status !== "loaded"}
      {...props}
    >
      <HugeiconsIcon icon={Copy01Icon} className="size-4" />
      <span className="sr-only">{copied ? "Copied!" : "Copy to clipboard"}</span>
    </Button>
  )
}

// ============================================================================
// AI IMAGE SKELETON
// ============================================================================

export interface AIImageSkeletonProps extends ComponentProps<"div"> {
  /** Width of the skeleton */
  width?: number | string
  /** Height of the skeleton */
  height?: number | string
}

export function AIImageSkeleton({
  width = 256,
  height = 256,
  className,
  ...props
}: AIImageSkeletonProps) {
  return (
    <div
      data-slot="ai-image-skeleton"
      className={cn(
        "animate-pulse rounded-2xl bg-muted",
        "flex items-center justify-center",
        className
      )}
      style={{ width, height }}
      {...props}
    >
      <HugeiconsIcon icon={Image01Icon} className="size-8 text-muted-foreground/50" />
    </div>
  )
}

// ============================================================================
// AI IMAGE GRID
// ============================================================================

export interface AIImageGridProps extends ComponentProps<"div"> {
  /** Number of columns */
  columns?: 1 | 2 | 3 | 4
}

export function AIImageGrid({ columns = 2, children, className, ...props }: AIImageGridProps) {
  const gridCols = {
    1: "grid-cols-1",
    2: "grid-cols-2",
    3: "grid-cols-3",
    4: "grid-cols-4",
  }

  return (
    <div
      data-slot="ai-image-grid"
      className={cn("grid gap-3", gridCols[columns], className)}
      {...props}
    >
      {children}
    </div>
  )
}
