// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Surface type enumeration for face classification
 *
 * This is the canonical definition used across all crates.
 * cadhy-cad reuses this type for consistency.
 */
export type SurfaceType =
  | "plane"
  | "cylinder"
  | "cone"
  | "sphere"
  | "torus"
  | "bezierSurface"
  | "bSplineSurface"
  | "revolutionSurface"
  | "extrusionSurface"
  | "offsetSurface"
  | "other"
